version: "3"

services:
  text-classification-web-service:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./docker:/text_classification
      - /text_classification/.local
      - /text_classification/.pyenv
      - /text_classification/.cache
    ports:
      - 10000:10000
    networks:
      - text-classification-net

networks:
  text-classification-net:
    driver: bridge